// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Bio       string       `json:"bio"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Book struct {
	ID          int32        `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	ISBN        string       `json:"ISBN"`
	GenreID     int32        `json:"genre_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type BooksAuthor struct {
	BookID       int32 `json:"book_id"`
	AuthorID     int32 `json:"author_id"`
	IsMainAuthor bool  `json:"is_main_author"`
}

type Genre struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type User struct {
	Username          string       `json:"username"`
	HashedPassword    string       `json:"hashed_password"`
	FullName          string       `json:"full_name"`
	Email             string       `json:"email"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
}
