// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	DeleteAuthor(ctx context.Context, id int32) error
	GetAuthor(ctx context.Context, id int32) (Author, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
}

var _ Querier = (*Queries)(nil)
